"""
.htaccess & Nginx Blocklist Generator
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Generates server-level access rules from Guard audit data to block
known-bad IPs and paths BEFORE PHP even boots. This provides edge-like
protection without requiring Cloudflare or a CDN.

Features:
    - Generates .htaccess deny rules (Apache/LiteSpeed)
    - Generates Nginx deny rules (nginx.conf snippet)
    - Auto-blocks IPs that triggered 10+ Guard BLOCKED events
    - Blocks known exploit paths (/xmlrpc.php, etc.) if not needed
    - Respects a whitelist to avoid locking out admins
"""

from __future__ import annotations

import logging
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger("cleanshift.htaccess_hardener")

# Known WordPress exploit paths to optionally block
_EXPLOIT_PATHS = {
    "xmlrpc.php":      "XML-RPC brute-force and DDoS amplification",
    "wp-trackback.php": "Trackback spam and pingback DDoS",
    "wp-config.php.bak": "Backup config file exposure",
    "wp-config.php~":    "Editor swap file exposure",
    ".env":              "Environment variable exposure",
    ".git/config":       "Git repository exposure",
    "debug.log":         "Debug log exposure",
    "error_log":         "Error log exposure",
}

# Default IP whitelist patterns (never block these)
_DEFAULT_WHITELIST = [
    "127.0.0.1",
    "::1",
]

# Maximum IPs in a single blocklist to prevent .htaccess bloat
_MAX_BLOCKLIST_IPS = 500


class HtaccessHardener:
    """Generates Apache .htaccess rules from Guard audit data."""

    def __init__(
        self,
        site_path: str,
        audit_db_path: str | None = None,
        whitelist: list[str] | None = None,
        min_blocks: int = 10,
    ):
        self.site_path = Path(site_path)
        self.audit_db_path = audit_db_path
        self.whitelist = set(whitelist or _DEFAULT_WHITELIST)
        self.min_blocks = min_blocks

    def get_blocked_ips_from_guard(self) -> list[dict[str, Any]]:
        """Query the Guard audit log for repeatedly blocked IPs.

        Returns IPs that have been blocked more than `min_blocks` times.
        """
        ips: list[dict[str, Any]] = []

        # Try reading from WordPress database via WP-CLI
        try:
            import subprocess
            result = subprocess.run(
                [
                    "wp", "db", "query",
                    f"SELECT user_ip, COUNT(*) as cnt "
                    f"FROM wp_cleanshift_audit_log "
                    f"WHERE verdict = 'BLOCKED' "
                    f"GROUP BY user_ip "
                    f"HAVING cnt >= {self.min_blocks} "
                    f"ORDER BY cnt DESC "
                    f"LIMIT {_MAX_BLOCKLIST_IPS}",
                    f"--path={self.site_path}",
                    "--allow-root",
                    "--skip-column-names",
                ],
                capture_output=True,
                text=True,
                timeout=30,
            )
            if result.returncode == 0:
                for line in result.stdout.strip().split("\n"):
                    if not line.strip():
                        continue
                    parts = line.split()
                    if len(parts) >= 2 and self._is_valid_ip(parts[0]):
                        ip = parts[0]
                        count = int(parts[1])
                        if ip not in self.whitelist:
                            ips.append({"ip": ip, "count": count})
        except Exception as e:
            logger.debug("Could not query Guard audit log: %s", e)

        return ips

    def generate_htaccess_rules(
        self,
        block_ips: list[dict[str, Any]] | None = None,
        block_xmlrpc: bool = True,
        block_file_access: bool = True,
        block_php_in_uploads: bool = True,
    ) -> str:
        """Generate .htaccess security rules.

        Returns the rules as a string to be inserted into .htaccess.
        """
        if block_ips is None:
            block_ips = self.get_blocked_ips_from_guard()

        lines = [
            "# ─── CleanShift Security Rules ───────────────────────────",
            f"# Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"# Blocked IPs: {len(block_ips)} (min {self.min_blocks} BLOCKED events)",
            "# DO NOT EDIT — regenerated by CleanShift agent",
            "# To disable: cleanshift harden --disable",
            "",
        ]

        # Block PHP execution in uploads directory
        if block_php_in_uploads:
            lines.extend([
                "# Block PHP execution in uploads (prevents uploaded backdoors)",
                "<IfModule mod_rewrite.c>",
                "    RewriteEngine On",
                "    RewriteRule ^wp-content/uploads/.*\\.ph(p[345s]?|tml|ar)$ - [F,L]",
                "</IfModule>",
                "",
            ])

        # Block known exploit paths
        if block_xmlrpc:
            lines.extend([
                "# Block XML-RPC (DDoS amplification / brute-force vector)",
                "<Files xmlrpc.php>",
                "    <IfModule mod_authz_core.c>",
                "        Require all denied",
                "    </IfModule>",
                "    <IfModule !mod_authz_core.c>",
                "        Order Deny,Allow",
                "        Deny from all",
                "    </IfModule>",
                "</Files>",
                "",
            ])

        # Block sensitive file access
        if block_file_access:
            lines.extend([
                "# Block access to sensitive files",
                '<FilesMatch "\\.(env|git|svn|sql|bak|swp|log)$">',
                "    <IfModule mod_authz_core.c>",
                "        Require all denied",
                "    </IfModule>",
                "    <IfModule !mod_authz_core.c>",
                "        Order Deny,Allow",
                "        Deny from all",
                "    </IfModule>",
                "</FilesMatch>",
                "",
            ])

        # IP blocklist
        if block_ips:
            lines.extend([
                f"# IP Blocklist — {len(block_ips)} IPs with {self.min_blocks}+ blocked events",
                "<IfModule mod_authz_core.c>",
                "    <RequireAll>",
                "        Require all granted",
            ])
            for entry in block_ips[:_MAX_BLOCKLIST_IPS]:
                lines.append(f"        Require not ip {entry['ip']}")
            lines.extend([
                "    </RequireAll>",
                "</IfModule>",
                "<IfModule !mod_authz_core.c>",
                "    Order Allow,Deny",
                "    Allow from all",
            ])
            for entry in block_ips[:_MAX_BLOCKLIST_IPS]:
                lines.append(f"    Deny from {entry['ip']}")
            lines.extend([
                "</IfModule>",
                "",
            ])

        lines.append("# ─── End CleanShift Security Rules ───────────────────────")
        return "\n".join(lines) + "\n"

    def generate_nginx_rules(
        self,
        block_ips: list[dict[str, Any]] | None = None,
        block_xmlrpc: bool = True,
        block_php_in_uploads: bool = True,
    ) -> str:
        """Generate Nginx deny rules snippet."""
        if block_ips is None:
            block_ips = self.get_blocked_ips_from_guard()

        lines = [
            "# ─── CleanShift Security Rules (Nginx) ────────────────────",
            f"# Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"# Include this in your server {{ }} block",
            "",
        ]

        # Block PHP in uploads
        if block_php_in_uploads:
            lines.extend([
                "# Block PHP execution in uploads",
                "location ~* /wp-content/uploads/.*\\.ph(p[345s]?|tml|ar)$ {",
                "    deny all;",
                "}",
                "",
            ])

        # Block xmlrpc
        if block_xmlrpc:
            lines.extend([
                "# Block XML-RPC",
                "location = /xmlrpc.php {",
                "    deny all;",
                "    return 403;",
                "}",
                "",
            ])

        # Block sensitive files
        lines.extend([
            "# Block sensitive files",
            "location ~* /\\.(env|git|svn) {",
            "    deny all;",
            "    return 404;",
            "}",
            "",
        ])

        # IP blocklist
        if block_ips:
            lines.extend([
                f"# IP Blocklist ({len(block_ips)} IPs)",
            ])
            for entry in block_ips[:_MAX_BLOCKLIST_IPS]:
                lines.append(f"deny {entry['ip']};")
            lines.append("")

        lines.append("# ─── End CleanShift Rules ──────────────────────────────")
        return "\n".join(lines) + "\n"

    def apply_to_htaccess(self, dry_run: bool = False) -> dict[str, Any]:
        """Apply security rules to the site's .htaccess file.

        Inserts rules between marker comments. Existing CleanShift rules
        are replaced; all other .htaccess content is preserved.

        Args:
            dry_run: If True, return the rules without writing.

        Returns:
            Dict with status, rules_added, ips_blocked.
        """
        htaccess_path = self.site_path / ".htaccess"
        blocked_ips = self.get_blocked_ips_from_guard()
        rules = self.generate_htaccess_rules(block_ips=blocked_ips)

        if dry_run:
            return {
                "status": "dry_run",
                "rules": rules,
                "ips_blocked": len(blocked_ips),
            }

        # Read existing .htaccess
        existing_content = ""
        if htaccess_path.exists():
            existing_content = htaccess_path.read_text(encoding="utf-8", errors="replace")

        # Remove old CleanShift rules
        marker_start = "# ─── CleanShift Security Rules"
        marker_end = "# ─── End CleanShift Security Rules"
        if marker_start in existing_content:
            pattern = re.compile(
                rf"{re.escape(marker_start)}.*?{re.escape(marker_end)}[^\n]*\n?",
                re.DOTALL,
            )
            existing_content = pattern.sub("", existing_content)

        # Prepend CleanShift rules (before WordPress rules for priority)
        new_content = rules + "\n" + existing_content.lstrip("\n")

        try:
            htaccess_path.write_text(new_content, encoding="utf-8")
            logger.info(
                "Applied %d IP blocks to %s",
                len(blocked_ips),
                htaccess_path,
            )
            return {
                "status": "applied",
                "ips_blocked": len(blocked_ips),
                "path": str(htaccess_path),
            }
        except OSError as e:
            logger.error("Failed to write .htaccess: %s", e)
            return {"status": "error", "error": str(e)}

    def remove_from_htaccess(self) -> dict[str, Any]:
        """Remove all CleanShift rules from .htaccess."""
        htaccess_path = self.site_path / ".htaccess"
        if not htaccess_path.exists():
            return {"status": "no_htaccess"}

        content = htaccess_path.read_text(encoding="utf-8", errors="replace")
        marker_start = "# ─── CleanShift Security Rules"
        marker_end = "# ─── End CleanShift Security Rules"

        if marker_start not in content:
            return {"status": "no_rules_found"}

        pattern = re.compile(
            rf"{re.escape(marker_start)}.*?{re.escape(marker_end)}[^\n]*\n?",
            re.DOTALL,
        )
        new_content = pattern.sub("", content).strip() + "\n"
        htaccess_path.write_text(new_content, encoding="utf-8")

        return {"status": "removed"}

    @staticmethod
    def _is_valid_ip(ip: str) -> bool:
        """Quick check if string looks like an IPv4 or IPv6 address."""
        # IPv4
        if re.match(r"^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$", ip):
            return True
        # IPv6 (simplified check)
        if ":" in ip and re.match(r"^[0-9a-fA-F:]+$", ip):
            return True
        return False
